"""Preset metrics and parametrized surfaces."""

from crr.presets.metrics import (
    cylinder_metric,
    euclidean_metric,
    hyperbolic_half_plane_metric,
    poincare_disk_metric,
    polar_metric,
    sphere_metric,
    torus_metric,
)
from crr.presets.relativity import (
    alcubierre_metric,
    anti_de_sitter_metric,
    de_sitter_metric,
    eddington_finkelstein_metric,
    flrw_metric,
    godel_metric,
    kerr_metric,
    kruskal_metric,
    kruskal_szekeres_metric,
    minkowski_metric,
    reissner_nordstrom_metric,
    robertson_walker_metric,
    schwarzschild_metric,
)
from crr.presets.surfaces import (
    catenoid_surface,
    cylinder_surface,
    helicoid_surface,
    mobius_strip_surface,
    plane_surface,
    sphere_surface,
    torus_surface,
)

__all__ = [
    "plane_surface",
    "sphere_surface",
    "cylinder_surface",
    "torus_surface",
    "catenoid_surface",
    "helicoid_surface",
    "mobius_strip_surface",
    "euclidean_metric",
    "polar_metric",
    "sphere_metric",
    "hyperbolic_half_plane_metric",
    "poincare_disk_metric",
    "cylinder_metric",
    "torus_metric",
    "minkowski_metric",
    "schwarzschild_metric",
    "flrw_metric",
    "robertson_walker_metric",
    "reissner_nordstrom_metric",
    "kerr_metric",
    "eddington_finkelstein_metric",
    "kruskal_metric",
    "kruskal_szekeres_metric",
    "godel_metric",
    "de_sitter_metric",
    "anti_de_sitter_metric",
    "alcubierre_metric",
]
