"""CRR: symbolic tools for curvature, Ricci, and Riemann tensors."""

from crr.core.coordinates import CoordinateChart
from crr.core.manifold import Manifold
from crr.core.metric import Metric
from crr.core.parametrized import ParametrizedMap
from crr.core.tensor import Tensor
from crr.forms import DifferentialForm
from crr.gauge import (
    GaugeCurvature,
    GaugePotential,
    abelian_gauge_potential,
    abelian_gauge_transform,
    covariant_exterior_derivative,
    infinitesimal_gauge_transform,
    yang_mills_action_density,
)
from crr.geometry.covariant_derivative import (
    covariant_derivative_covariant_2tensor,
    covariant_derivative_covector,
    covariant_derivative_scalar,
    covariant_derivative_vector,
)
from crr.geometry.global_invariants import GaussBonnetResult, gauss_bonnet_check
from crr.numeric.geodesic_solver import GeodesicSolution, solve_geodesic
from crr.lie import (
    AlgebraValuedForm,
    LieAlgebra,
    LieAlgebraElement,
    abelian_lie_algebra,
    heisenberg_algebra,
    matrix_commutator,
    matrix_lie_algebra_from_basis,
    sl2r_algebra,
    so2_algebra,
    so3_algebra,
    su2_algebra,
)
from crr.presets import (
    alcubierre_metric,
    anti_de_sitter_metric,
    catenoid_surface,
    cylinder_metric,
    cylinder_surface,
    de_sitter_metric,
    eddington_finkelstein_metric,
    euclidean_metric,
    flrw_metric,
    godel_metric,
    helicoid_surface,
    hyperbolic_half_plane_metric,
    kerr_metric,
    kruskal_metric,
    kruskal_szekeres_metric,
    minkowski_metric,
    mobius_strip_surface,
    plane_surface,
    poincare_disk_metric,
    polar_metric,
    reissner_nordstrom_metric,
    robertson_walker_metric,
    schwarzschild_metric,
    sphere_metric,
    sphere_surface,
    torus_metric,
    torus_surface,
)

__all__ = [
    "CoordinateChart",
    "Manifold",
    "Metric",
    "ParametrizedMap",
    "Tensor",
    "DifferentialForm",
    "GaugePotential",
    "GaugeCurvature",
    "LieAlgebra",
    "LieAlgebraElement",
    "AlgebraValuedForm",
    "covariant_derivative_scalar",
    "covariant_derivative_vector",
    "covariant_derivative_covector",
    "covariant_derivative_covariant_2tensor",
    "GeodesicSolution",
    "solve_geodesic",
    "abelian_lie_algebra",
    "so2_algebra",
    "so3_algebra",
    "su2_algebra",
    "sl2r_algebra",
    "heisenberg_algebra",
    "matrix_commutator",
    "matrix_lie_algebra_from_basis",
    "abelian_gauge_potential",
    "covariant_exterior_derivative",
    "abelian_gauge_transform",
    "infinitesimal_gauge_transform",
    "yang_mills_action_density",
    "GaussBonnetResult",
    "gauss_bonnet_check",
    "plane_surface",
    "sphere_surface",
    "cylinder_surface",
    "torus_surface",
    "catenoid_surface",
    "helicoid_surface",
    "mobius_strip_surface",
    "euclidean_metric",
    "polar_metric",
    "sphere_metric",
    "hyperbolic_half_plane_metric",
    "poincare_disk_metric",
    "cylinder_metric",
    "torus_metric",
    "minkowski_metric",
    "schwarzschild_metric",
    "flrw_metric",
    "robertson_walker_metric",
    "reissner_nordstrom_metric",
    "kerr_metric",
    "eddington_finkelstein_metric",
    "kruskal_metric",
    "kruskal_szekeres_metric",
    "godel_metric",
    "de_sitter_metric",
    "anti_de_sitter_metric",
    "alcubierre_metric",
]
